### ISSUE TITLE
“On-the-fly” GDSII writing example

### ISSUE THREAD

**Issue by martty** [nrc-cnrc/Raith_GDSII#2]
Great library! Thank you very much for it, made my work much easier.

In the example for “On-the-fly” GDSII writing,

`FileID=fopen('C:\Users\Public\Documents\ringarray.csf','w');`

This will flush the file after each call to `fwrite` - of which there are plenty of even for 1 call of `Raith_library.writeelement`. I'd suggest amending the section to suggest opening the file with 'W', the speedup is very significant. It is probably worthwhile to change the `fopen` call in `Raith_library.writegds` too.

**Comment by ahryciw** [comment]
Hi Marcell,

Many thanks the 'W' vs. 'w' suggestion—I'll implement this in the next
update.  I'm very glad you've found this library helpful for your work.

Cheers,

 – Aaron




Aaron Hryciw, PhD, PEng

Fabrication Group Manager

University of Alberta - nanoFAB

W1-060 ECERF Building

9107 - 116 Street

Edmonton, Alberta

Canada T6G 2V4 Ph: 780-940-7938
www.nanofab.ualberta.ca

**Comment by ahryciw** [comment]
Buffered writing ('W' flag in `fopen`) implemented in `Raith_library.writegds` and examples in user manual.
