### ISSUE TITLE
function to substract/merge/differential of two structures

### ISSUE THREAD

**Issue by smeanapole** [nrc-cnrc/Raith_GDSII#3]
Fantastic library! I really appreciate it to ease my work in these years. I recently met an issue to create a hole structure where the inner radius is not at the center (non-concentric).

Now I have to design two disks and then manually substract them in the Raith software. This becomes even challenging when I put two holes in a microdisk. Is there a simple solution to do this?

Many thanks in advance!

Yi

**Comment by ahryciw** [comment]
Hi Yi,

Many thanks for your comments—I'm very glad you've found the Raith_GDSII
toolbox useful.  Boolean operations (and Boolean subtraction in
particular), is the #1 feature request that I receive.  It is on my roadmap
eventually to add this functionality to the toolbox, but it is non-trivial
to do so for a general case in a way that returns the simple polygons
required by GDSII (MATLAB's native Boolean operations on patch elements
don't actually return weakly simple polygons).  I know such algorithms
exist, but I have not had the time to track them down and implement them in
the toolbox.

As a workaround, for your case, I would recommend writing your own function
which does this Boolean subtraction "by hand" to create the desired
structure, which can then be instantiated as necessary.  I've attached a
function which does this, assuming I understand your geometry properly:  it
returns a Raith_structure object consisting of a disc, centred at the
origin, with a disc-shaped hole, centred at (*d*,0).  To improve smoothness
of the sidewalls, you can optionally outline the disc and hole edges with
rings (Raith curved elements) of width *w*; if no outlining is
required, *w* can
be left out.

For instance, here is a 10 µm disc with a 5 µm hole offset from the centre
by 1 µm, without outlining:

>> S = dischole('foo',0,1,10,5,100,1);
[image: image.png]

Is this what you have in mind?

Cheers,

– Aaron





Aaron Hryciw, PhD, PEng

Fabrication Group Manager

University of Alberta - nanoFAB

W1-060 ECERF Building

9107 - 116 Street

Edmonton, Alberta

Canada T6G 2V4 Ph: 780-940-7938
www.nanofab.ualberta.ca
