### ISSUE TITLE
Raith_Library.plotedges loses translation/magnification information after plotting an "aref" element

### ISSUE THREAD

**Issue by goluiz** [nrc-cnrc/Raith_GDSII#4]
This happens when calling `Raith_positionlist.poltedges` with several elements in the library. More specifically when "aref" elements are present. The function works fine for the first "aref" instance to be plotted (and all simpler elements before), but all elements after that lose the translation inserted in the positionlist creation.

The issue seems to stem from the fact that the magnification/translation matrix is reset to zero when plotting "aref" in the `Raith_Library.plotedges` function. This was taken care of in the plot function by the insertion of a local "M2" variable.

**Comment by ahryciw** [comment]
Issue will be resolved in new repo location [ahryciw/Raith_GDSII](https://github.com/ahryciw/Raith_GDSII).
